### ISSUE TITLE
Scoreboard not listing players

### ISSUE THREAD

**Issue by MasonMollyy** [XLabsProject/iw6x-client#100]
Scoreboard doesn't show more than 1 person per team, doesn't happen everytime to me but fairly often, most of my mates seem to get it most of the time when in any Tdm dedi. 

Note:It's only on dedicated servers.

**Comment by momo5502** [comment]
Please try to isolate the commit

**Comment by OneFourOne** [comment]
Sometimes it just shows yourself, tested on a server with two people.

**Comment by momo5502** [comment]
> Please try to isolate the commit

Kinda retarded comment, ngl.
@Joelrau's added functions to switch between extinction and the core game will solve this issue. I will add a feture so that the connect command and the map command switch to the appropriate mode. This should solve all issues and add support for extinction at the same time

**Comment by Joelrau** [comment]
If you connect from ONLINE GAME, the scoreboard shows normally, but if you connect without pressing ONLINE PLAY first, it gets bugged.
