### ISSUE TITLE
Fatal Error Server Crash

### ISSUE THREAD

**Issue by efinst0rm** [XLabsProject/iw6x-client#119]
After a few rounds server would crash.

[crashdump.zip](https://github.com/XLabsProject/iw6x-client/files/5443250/crashdump.zip)

**Comment by momo5502** [comment]
Probably the same as #111

**Comment by momo5502** [comment]
Those are in fact two different crashes you uploaded. One wants to calculate lighting for Fx rendering, and the other one is the same as #111

**Comment by efinst0rm** [comment]
Got a few more crash dumps.
https://cdn.discordapp.com/attachments/265852764238774273/773308540135145502/09PzQynaoyHrwKN4zwEH.png
[crashdump.zip](https://github.com/XLabsProject/iw6x-client/files/5484359/crashdump.zip)

**Comment by efinst0rm** [comment]
Using test build in discord got this crash.
https://cdn.discordapp.com/attachments/265852764238774273/774276819774865408/w5XoZJjuttvrPdSZjWfS.png
[minidumps.zip](https://github.com/XLabsProject/iw6x-client/files/5501691/minidumps.zip)

**Comment by momo5502** [comment]
![Uploading image.png…]()

**Comment by momo5502** [comment]
This should be fixed now. Going to document my fix

**Comment by momo5502** [comment]
This issue is related to crashes inside Arxan.
I assume opaque predicates were injected into the game.
If so, this crash is due to opaque predicates evaluating wrong and resulting in the wrong path being taken.

All the debugging tools I wrote to trace down the issue, can be found on the arxan-test branch: https://github.com/XLabsProject/iw6x-client/tree/arxan-test

**Comment by momo5502** [comment]
Here are the traces I recorded to tack down the issue:

[crash-analysis.zip](https://github.com/XLabsProject/iw6x-client/files/5599116/crash-analysis.zip)
