### ISSUE TITLE
Add a visual ping by server on the server browser

### ISSUE THREAD

**Issue by FragsAreUs** [XLabsProject/iw6x-client#266]
I know in the code the servers are sorted by ping by default but I have got dmed by one person who runs server for tekno and pluto and some iw4x and said it would be nice to see the servers ping on the side as some people decide if they join or not by the ping and and not by players some times.

**Comment by FragsAreUs** [comment]
I have attempted to do it by looking on how iw4x did it but was to retarded to get it to work, I know if its done and I look at the code I am probably going to slap my self

**Comment by momo5502** [comment]
This requires the lua menus to be edited. It's not an easy task

**Comment by hosseinpourziyaie** [comment]
patching menu files definitely is not solution you should think of. considering how hard and painful is it.

one simple way I came up with was appending ping to one of data fields already exists

I tried appending in front of server name but I failed lining them up correctly (due to variety of characters width)

only choice I left with was adding it in front of players count. to do so you can:

1- Replace line 133 of  ``server_list.cpp`` component with this
```return utils::string::va("%02d/%02d       [%03d]\n", servers[i].clients, servers[index].max_clients, servers[i].ping);```

2- Then add localized string override for desired field(line 333 of same file)

```localized_strings::override("MENU_NUMPLAYERS", "#Players     Ping");```

It will look like this:
![iw6x 2020-12-27 21-18-33-065](https://user-images.githubusercontent.com/22142481/103176772-fac70b00-4889-11eb-8874-70547a65c5b0.jpg)

You can Also swap playerscount column with type column(last field) for better looking design:
![iw6x 2020-12-27 21-10-06-335](https://user-images.githubusercontent.com/22142481/103176873-9eb0b680-488a-11eb-9769-3fc75530c610.jpg)


it may not be big deal and its still not that accurate lined-up but it does the job.

**Comment by momo5502** [comment]
No front, but that's an extremely ugly solution. Editing the lua menu is the only reasonable solution.

**Comment by hosseinpourziyaie** [comment]
I already mentioned above. Its not best possible way and yeah its ugly. but **it does the job for now**

Then you can replace it with new menu written whenever you manage to patch menu assets
