### ISSUE TITLE
Stuck On Map Loading Screen

### ISSUE THREAD

**Issue by Krayziey** [XLabsProject/iw6x-client#613]
Whenever I try to play a private match or join a multiplayer server it's just stuck on the map loading screen, it's not frozen because the load animation still moves, the client only make me join extinction servers and that's it.

**Comment by MakuAureo** [comment]
I've found a "workaround", in your game files there's a folder called zone, by removing the techsets_mp_(map file name).ff inside that folder it doesn't get stuck on the loading screen. Doing this makes the map looks terrible but at least it is playable, although it will crash at some point.

**Comment by diamante0018** [comment]
Try following the repair guide on our website https://xlabs.dev/iw6x_repair

Because this issue does not provide any useful information to work with I shall close it in a bit if we don't hear back from you. You should join our discord server and seek help there if you still have issue after following the repair guide.

**Comment by diamante0018** [comment]
Please use the xlabs launcher to open the game in the future, also you may follow the advice you have been given in this thread.
I will now close it has I haven't heard back from you.
