### ISSUE TITLE
crash while typing message in chat.

### ISSUE THREAD

**Issue by CoNNoUK** [XLabsProject/iw6x-client#99]
added dump files and iw6x.exe screen shot http://prntscr.com/v55zu0
[ghost_crash.zip](https://github.com/XLabsProject/iw6x-client/files/5428671/ghost_crash.zip)
src debug build @/dev/urandom Remove trigger for PRs as secrets won't work for that. (0a95ae1).
using the game in windowed mode.

**Comment by skiff** [comment]
Based on your screenshot, and saying that you used a debug build, I'm going to go out on a limb and say the issue has nothing to do with chat. There has been an issue with overhead names in the debug builds. Whenever an overhead name would come onto screen, that is what causes the crash and it's only happening on debug builds. With the character position in your screenshot I would say that is likely the issue here
